version: 2
updates:
  - package-ecosystem: "pip"
    directory: "app/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "pipeline/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "training/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "scripts/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "tests/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
